In [1]:
import numpy as np
import math as m

In [21]:
data = np.load('/Users/jonathanperalgort/Documents/CMPT353-Computational-Data-Science/Exercises/1/e1/monthdata.npz') #loading the monthdata.npz file

In [3]:
totals = data['totals']

In [4]:
counts = data['counts']

In [5]:
totals

array([[1809, 1482, 2159,  374,  606,  428,  442,   68,  956, 1429, 1349,
        1846],
       [ 121,   22,   46,   40,  683,  616, 2061,  834,  253,  276,   27,
         224],
       [ 896, 1232,  992, 1106, 1236, 1015, 1264, 1096, 1026, 2422, 1184,
        1099],
       [1491, 1473, 1452, 1595, 1001,  725,  734,  445,  845, 2185, 1305,
        1835],
       [ 930,  561,  533,  204,  546,  748,  662,  274,  785, 1620, 1293,
         295],
       [ 183,  982,  621,  471,  667,  671,  525, 1599,  433, 1176,  594,
         627],
       [ 363,  491,  729,  681,  346,  269,  399,  667,  663,  452,  497,
         821],
       [1682, 1304, 1616,  242,  516,  582,  328,  138,  784, 2034, 2402,
        1520],
       [ 220,   90,   28,  120,   98,  306,  154,  280,  488,  158,  176,
         116]])

In [6]:
counts

array([[30, 22, 30, 30, 21, 21, 20, 25, 20, 19, 17, 16],
       [31, 29, 31, 30, 31, 30, 31, 30, 30, 30, 30, 30],
       [31, 29, 31, 30, 30, 30, 31, 31, 30, 31, 30, 31],
       [31, 29, 31, 30, 31, 30, 31, 31, 29, 30, 30, 31],
       [31, 29, 31, 29, 31, 29, 30, 31, 30, 31, 30, 29],
       [31, 29, 31, 30, 31, 30, 28, 31, 30, 30, 29, 31],
       [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 29, 31],
       [30, 28, 31, 30, 30, 29, 30, 31, 30, 31, 30, 30],
       [31, 28, 31, 30, 31, 30, 31, 31, 30, 30, 30, 30]])

In [7]:
#m.floor(np.argmin(totals, axis=None) / 12)

In [8]:
sum_of_precipitations_per_location = np.sum(totals, axis=1) 

In [9]:
sum_of_precipitations_per_location #sum of monthly precipitations per location

array([12948,  5203, 14568, 15086,  8451,  8549,  6378, 13148,  2234])

In [10]:
np.argmin(sum_of_precipitations_per_location) #Displays the location with the least precipitation throughout the year

8

In [11]:
totals/counts

array([[ 60.3       ,  67.36363636,  71.96666667,  12.46666667,
         28.85714286,  20.38095238,  22.1       ,   2.72      ,
         47.8       ,  75.21052632,  79.35294118, 115.375     ],
       [  3.90322581,   0.75862069,   1.48387097,   1.33333333,
         22.03225806,  20.53333333,  66.48387097,  27.8       ,
          8.43333333,   9.2       ,   0.9       ,   7.46666667],
       [ 28.90322581,  42.48275862,  32.        ,  36.86666667,
         41.2       ,  33.83333333,  40.77419355,  35.35483871,
         34.2       ,  78.12903226,  39.46666667,  35.4516129 ],
       [ 48.09677419,  50.79310345,  46.83870968,  53.16666667,
         32.29032258,  24.16666667,  23.67741935,  14.35483871,
         29.13793103,  72.83333333,  43.5       ,  59.19354839],
       [ 30.        ,  19.34482759,  17.19354839,   7.03448276,
         17.61290323,  25.79310345,  22.06666667,   8.83870968,
         26.16666667,  52.25806452,  43.1       ,  10.17241379],
       [  5.90322581,  33.86206897,

In [12]:
sum_of_monthly_precipitations = np.sum(totals, axis=1) #sum of total monthly precipitations

In [13]:
sum_of_monthly_precipitations

array([12948,  5203, 14568, 15086,  8451,  8549,  6378, 13148,  2234])

In [14]:
sum_of_counts = np.sum(counts, axis=1) #sum of counts
sum_of_counts

array([271, 363, 365, 364, 361, 361, 364, 360, 363])

In [15]:
sum_of_monthly_precipitations / sum_of_counts #Divided by twelve to figure out the average precipitation in a city per year

array([47.77859779, 14.33333333, 39.91232877, 41.44505495, 23.4099723 ,
       23.68144044, 17.52197802, 36.52222222,  6.15426997])

In [16]:
totals.shape

(9, 12)

In [17]:
#new_totals will contain the reshaped totals array with the precipitations of the corresponding quarter
new_totals = totals

In [18]:
new_totals = np.reshape(new_totals, (9,4,3))

In [19]:
sum_of_quarters = np.sum(new_totals, axis=2) #contains the sum of all the quarters in the year for all 9 locations

In [20]:
sum_of_quarters/3 #displays the average of precipitations per quarter for each of the 9 locations

array([[1816.66666667,  469.33333333,  488.66666667, 1541.33333333],
       [  63.        ,  446.33333333, 1049.33333333,  175.66666667],
       [1040.        , 1119.        , 1128.66666667, 1568.33333333],
       [1472.        , 1107.        ,  674.66666667, 1775.        ],
       [ 674.66666667,  499.33333333,  573.66666667, 1069.33333333],
       [ 595.33333333,  603.        ,  852.33333333,  799.        ],
       [ 527.66666667,  432.        ,  576.33333333,  590.        ],
       [1534.        ,  446.66666667,  416.66666667, 1985.33333333],
       [ 112.66666667,  174.66666667,  307.33333333,  150.        ]])